# Generated by Django 5.0.3 on 2024-03-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='email',
            field=models.CharField(default='no_email', max_length=200),
            preserve_default=False,
        ),
    ]
