# Generated by Django 5.0.3 on 2024-03-13 21:47

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_siteuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file',
            field=models.FileField(null=True, storage=myapp.models.CustomS3Boto3Storage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='userfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
