# Generated by Django 5.0.3 on 2024-03-26 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userfile_file_userfile_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NR', 'Not reviewed'), ('IP', 'In progress'), ('RE', 'Resolved')], default='NR', max_length=2)),
                ('comments', models.CharField(default='', max_length=1000)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userfile')),
            ],
        ),
    ]
