# Generated by Django 5.0.3 on 2024-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='comments',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userfile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not reviewed'), (1, 'In progress'), (2, 'Resolved')], default=0),
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
    ]
