# Generated by Django 5.0.2 on 2024-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userfile_comments_userfile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='comments',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
