# Generated by Django 5.0.3 on 2024-04-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_userfile_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('General Mental Health', 'General Mental Health'), ('Academic', 'Academic'), ('Substance Abuse', 'Substance Abuse'), ('Other', 'Other')], max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.siteuser')),
                ('user_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userfile')),
            ],
        ),
    ]
