# Generated by Django 5.0.3 on 2024-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_reportform'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportform',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not reviewed'), (1, 'In progress'), (2, 'Resolved')], default=0),
        ),
    ]
