# Generated by Django 5.0.3 on 2024-04-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_reportform_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='status',
        ),
        migrations.AlterField(
            model_name='reportform',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Reviewed'), (1, 'In Progress'), (2, 'Resolved')], default=0),
        ),
    ]
