# Generated by Django 5.0.3 on 2024-04-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_userfile_comments_remove_userfile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportform',
            name='status2',
            field=models.CharField(choices=[('Not Yet Reviewed', 'Not Yet Reviewed'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Not Yet Reviewed', max_length=50),
        ),
    ]
