# Generated by Django 5.0.3 on 2024-04-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_reportform_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportform',
            name='status',
        ),
    ]
