# Generated by Django 5.0.3 on 2024-04-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_reportform_comments_alter_siteuser_oauth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
