# Generated by Django 5.0.3 on 2024-04-27 00:59

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_siteuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='profile_picture',
            field=models.FileField(null=True, storage=myapp.models.CustomS3Boto3Storage(), upload_to=''),
        ),
    ]
